# Generated by Django 5.2.8 on 2025-12-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='dr',
            new_name='doctor',
        ),
    ]
