# Generated by Django 5.2.8 on 2025-12-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_resource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="hours",
        ),
        migrations.AddField(
            model_name="resource",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
